### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
If my pull request is accepted, and if you tag the software, I can create an opam
package so that people can install your (interesting) software automatically.
Thanks a lot.

**Comment by masateruk** [comment]
Thank you for your pull request.

I've merged your commits.

**Comment by masateruk** [comment]
I add a tag v0.1. 
Can you create an opam package if possible ?

Thank you for any help you can provide.

**Comment by UnixJunkie** [comment]
OK, I try.

**Comment by UnixJunkie** [comment]
The pull request for opam was sent:
https://github.com/ocaml/opam-repository/pull/3890
the maintainer field in the package description means package maintainer, not software maintainer

**Comment by masateruk** [comment]
Thank you for your help.

**Pull request merged**
